### ISSUE TITLE
报错，请问该工具是运行在python几版本下的

### ISSUE THREAD

**Issue by uuuuuuzeus** [rabbitmask/WeblogicScan#8]
Building wheel for fake-useragent (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /usr/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-crLfxT/fake-useragent/setup.py'"'"'; __file__='"'"'/tmp/pip-install-crLfxT/fake-useragent/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-pmvAoj    
       cwd: /tmp/pip-install-crLfxT/fake-useragent/                               
  Complete output (6 lines):                                                      
  usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]           
     or: setup.py --help [cmd1 cmd2 ...]                                          
     or: setup.py --help-commands                                                 
     or: setup.py cmd --help                                                      
                                                                                  
  error: invalid command 'bdist_wheel'                                            
  ----------------------------------------                                        
  ERROR: Failed building wheel for fake-useragent
  Running setup.py clean for fake-useragent
Failed to build fake-useragent
Installing collected packages: fake-useragent, urllib3, certifi, idna, requests
    Running setup.py install for fake-useragent ... done
Successfully installed certifi-2020.11.8 fake-useragent-0.1.11 idna-2.10 requests-2.23.0 urllib3-1.25.11
root@kali:/home/kali/myTools/weblogic_scan/WeblogicScan_tools_1# python2.7 WeblogicScan.py  -u 124.95.133.164 -p 7001
Traceback (most recent call last):
  File "WeblogicScan.py", line 12, in <module>
    from config.config_banners import banner
ImportError: No module named config.config_banners

**Comment by rabbitmask** [comment]
是py3哦~py2官方已经抛弃啦~

**Comment by ziya1666** [comment]
Traceback (most recent call last):
  File "/Users/yangzichao3/Documents/Toolkits/WeblogicScan/WeblogicScan.py", line 12, in <module>
    from config.config_banners import banner
ModuleNotFoundError: No module named 'config.config_banners'

python版本3.9.6 报错不可用

**Comment by Polaris-L** [comment]
> Traceback (most recent call last): File "/Users/yangzichao3/Documents/Toolkits/WeblogicScan/WeblogicScan.py", line 12, in from config.config_banners import banner ModuleNotFoundError: No module named 'config.config_banners'
> 
> python版本3.9.6 报错不可用
你这个是同时装了python2和3，忘记用python3运行了吧，我之前手残也忘了，报错一模一样
